(async function(){
  const rules = await APP.loadJSON("data/rules.json");
  const state = APP.loadState();
  const params = new URLSearchParams(location.search);
  const id = params.get("match");
  const m = state.matches?.[id];
  const el = document.getElementById("wrap");
  if(!m){ el.innerHTML="<h2>Match not found.</h2>"; return; }

  function inningsHTML(inn){
    if(!inn) return "";
    const bowlers = Object.values(inn.bowlers||{});
    return `
      <div class="card" style="margin-bottom:12px">
        <h3>${inn.battingTeam} — ${inn.runs}/${inn.wkts} (${APP.fmtOverBalls(inn.balls)} ov)</h3>
        <hr class="sep"/>
        <h4 style="margin:0 0 8px">Batting</h4>
        <div style="overflow:auto">
          <table class="table">
            <thead><tr><th>Batsman</th><th>R</th><th>B</th><th>4s</th><th>6s</th><th>Status</th></tr></thead>
            <tbody>
              ${inn.batsmen.map(b=>`
                <tr>
                  <td>${b.name}</td>
                  <td class="mono">${b.r}</td>
                  <td class="mono">${b.b}</td>
                  <td class="mono">${b._4}</td>
                  <td class="mono">${b._6}</td>
                  <td>${b.out ? `${b.how || "Out"} ${b.by?`(by ${b.by})`:""}` : "Not out"}</td>
                </tr>`).join("")}
            </tbody>
          </table>
        </div>

        <hr class="sep"/>
        <h4 style="margin:0 0 8px">Bowling</h4>
        <div style="overflow:auto">
          <table class="table">
            <thead><tr><th>Bowler</th><th>O</th><th>R</th><th>W</th><th>Wd</th><th>Nb</th></tr></thead>
            <tbody>
              ${bowlers.map(b=>`
                <tr>
                  <td>${b.name}</td>
                  <td class="mono">${APP.fmtOverBalls(b.balls)}</td>
                  <td class="mono">${b.runs}</td>
                  <td class="mono">${b.wkts}</td>
                  <td class="mono">${b.wides}</td>
                  <td class="mono">${b.noballs}</td>
                </tr>`).join("")}
            </tbody>
          </table>
        </div>
      </div>
    `;
  }

  el.innerHTML = `
    <div class="card">
      <div class="row" style="justify-content:space-between; align-items:flex-start">
        <div>
          <div class="small">MPGB Premier League 2025-26</div>
          <div style="font-size:22px; font-weight:900">${m.teamA} vs ${m.teamB}</div>
          <div class="small">Match ID: <span class="mono">${m.id}</span> • Group ${m.group} • ${m.venue||"-"} • ${m.time||"-"}</div>
        </div>
        <button class="btn ok" onclick="window.print()">Print / Save PDF</button>
      </div>
      <hr class="sep"/>
      <div class="small">Format: ${rules.format.overs_per_innings} overs • Powerplay: ${rules.format.powerplay_overs} overs • Bowler max: ${rules.format.max_overs_per_bowler} overs • No LBW</div>
    </div>
    <div style="height:12px"></div>
    ${inningsHTML(m.innings1)}
    ${inningsHTML(m.innings2)}
    <div class="footer">Generated by MPGB Premier League Web App • Use browser Print → Save as PDF</div>
  `;
})();